name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-dita:
    name: Build DITA
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Build PDF
        uses: jason-fox/dita-build-action@master
        with:
          install: |
            apt install -y --no-install-recommends nodejs
            nodejs -v
          plugins: |
            org.doctales.xmltask
            fox.jason.extend.css
            fox.jason.prismjs
          input: document.ditamap
          transtype: pdf
          output-path: out
      - name: Build HTML5 + Bootstrap
        uses: jason-fox/dita-build-action@master
        with:
          install: setup.sh
          plugins: |
            net.infotexture.dita-bootstrap
            org.doctales.xmltask
            fox.jason.extend.css
            fox.jason.prismjs
          input: document.ditamap
          transtype: html5-bootstrap
          output-path: out
      - name: Upload DITA
        uses: actions/upload-artifact@v2
        with:
          name: dita-artifact
          path: 'out'
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.